In [1]:
d1 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,9,10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,22,23,24]
}

In [2]:
d1

{'key1': [1, 2, 3, 4, 5, 'sudh'],
 'key2': [7, 8, 9, 10, 11, 12],
 'key3': [13, 14, 15, 16, 17, 18],
 'key4': [19, 20, 21, 22, 23, 24]}

In [3]:
import pandas as pd 

In [5]:
df1 = pd.DataFrame(d1 )  # but same len in each key then only it won't give error

In [6]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [7]:
d2 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [8]:
d2

{'key1': [1, 2, 3, 4, 5, 'sudh'],
 'key2': [7, 8, 'kumar', 10, 11, 12],
 'key3': [13, 14, 15, 16, 17, 18],
 'key4': [19, 20, 21, 'ineuron', 'pwskills', 24]}

In [9]:
df2 = pd.DataFrame(d2)

In [10]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [11]:
df2

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [12]:
pd.merge(df1,df2,how= 'outer',on= ['key4','key1'])

/tmp/ipykernel_3352/1864705398.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2,how= 'outer',on= ['key4','key1'])


key1  key2_x  key3_x      key4 key2_y  key3_y
0     1     7.0    13.0      19.0      7    13.0
1     2     8.0    14.0      20.0      8    14.0
2     3     9.0    15.0      21.0  kumar    15.0
3     4    10.0    16.0      22.0    NaN     NaN
4     5    11.0    17.0      23.0    NaN     NaN
5  sudh    12.0    18.0      24.0     12    18.0
6     4     NaN     NaN   ineuron     10    16.0
7     5     NaN     NaN  pwskills     11    17.0

In [13]:
pd.merge(df1,df2,how= 'left',on= 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7    13.0
1      2       8      14   20      2      8    14.0
2      3       9      15   21      3  kumar    15.0
3      4      10      16   22    NaN    NaN     NaN
4      5      11      17   23    NaN    NaN     NaN
5   sudh      12      18   24   sudh     12    18.0

In [14]:
pd.merge(df1,df2,how= 'inner',on= 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7      13
1      2       8      14   20      2      8      14
2      3       9      15   21      3  kumar      15
3   sudh      12      18   24   sudh     12      18

In [15]:
pd.merge(df1,df2,how= 'inner',on= 'key1')

key1  key2_x  key3_x  key4_x key2_y  key3_y    key4_y
0     1       7      13      19      7      13        19
1     2       8      14      20      8      14        20
2     3       9      15      21  kumar      15        21
3     4      10      16      22     10      16   ineuron
4     5      11      17      23     11      17  pwskills
5  sudh      12      18      24     12      18        24

In [16]:
pd.merge(df1,df2)

key1 key2  key3 key4
0     1    7    13   19
1     2    8    14   20
2  sudh   12    18   24

In [17]:
d11 = {'a':[1,2,3,4,5,"sudh"],
      'b' : [7,8,9,10,11,12],
      'c':[13,14,15,16,17,18],
      'd':[19,20,21,22,23,24]
}

In [18]:
d12 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [19]:
df11 = pd.DataFrame(d11)


In [20]:
df11

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [21]:
df12 = pd.DataFrame(d12)

In [22]:
df12

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [23]:
pd.merge(df11, df12 , how = 'left' , left_on = 'a' , right_on='key1')

a   b   c   d  key1   key2  key3      key4
0     1   7  13  19     1      7    13        19
1     2   8  14  20     2      8    14        20
2     3   9  15  21     3  kumar    15        21
3     4  10  16  22     4     10    16   ineuron
4     5  11  17  23     5     11    17  pwskills
5  sudh  12  18  24  sudh     12    18        24

In [24]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [25]:
df2

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [26]:
d10 = {'key11':[1,2,3,4,5,"sudh"],
      'key21' : [7,8,9,10,11,12],
      'key31':[13,14,15,16,17,18],
      'key41':[19,20,21,22,23,24]
}

In [27]:
d20 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [28]:
df10 = pd.DataFrame(d10 , index = [1,2,3,4,5,6])

In [29]:
df20 = pd.DataFrame(d20, index=[1,2,3,4,5,'sudh'])

In [30]:
df10

key11  key21  key31  key41
1     1      7     13     19
2     2      8     14     20
3     3      9     15     21
4     4     10     16     22
5     5     11     17     23
6  sudh     12     18     24

In [31]:
df20

key1   key2  key3      key4
1        1      7    13        19
2        2      8    14        20
3        3  kumar    15        21
4        4     10    16   ineuron
5        5     11    17  pwskills
sudh  sudh     12    18        24

In [32]:
df10.join(df20,how = 'right')

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0     1      7    13        19
2        2    8.0   14.0   20.0     2      8    14        20
3        3    9.0   15.0   21.0     3  kumar    15        21
4        4   10.0   16.0   22.0     4     10    16   ineuron
5        5   11.0   17.0   23.0     5     11    17  pwskills
sudh   NaN    NaN    NaN    NaN  sudh     12    18        24

In [33]:
df10.join(df20)

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7  13.0        19
2     2      8     14     20    2      8  14.0        20
3     3      9     15     21    3  kumar  15.0        21
4     4     10     16     22    4     10  16.0   ineuron
5     5     11     17     23    5     11  17.0  pwskills
6  sudh     12     18     24  NaN    NaN   NaN       NaN

In [34]:
df10.join(df20 , how = 'outer')

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0     1      7  13.0        19
2        2    8.0   14.0   20.0     2      8  14.0        20
3        3    9.0   15.0   21.0     3  kumar  15.0        21
4        4   10.0   16.0   22.0     4     10  16.0   ineuron
5        5   11.0   17.0   23.0     5     11  17.0  pwskills
6     sudh   12.0   18.0   24.0   NaN    NaN   NaN       NaN
sudh   NaN    NaN    NaN    NaN  sudh     12  18.0        24

In [35]:
df10.join(df20 , how = 'inner')

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7    13        19
2     2      8     14     20    2      8    14        20
3     3      9     15     21    3  kumar    15        21
4     4     10     16     22    4     10    16   ineuron
5     5     11     17     23    5     11    17  pwskills

In [36]:
df10

key11  key21  key31  key41
1     1      7     13     19
2     2      8     14     20
3     3      9     15     21
4     4     10     16     22
5     5     11     17     23
6  sudh     12     18     24

In [37]:
df20

key1   key2  key3      key4
1        1      7    13        19
2        2      8    14        20
3        3  kumar    15        21
4        4     10    16   ineuron
5        5     11    17  pwskills
sudh  sudh     12    18        24

In [38]:
pd.concat([df1,df2] , axis=0)

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3      9    15        21
3     4     10    16        22
4     5     11    17        23
5  sudh     12    18        24
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [39]:
pd.concat([df1,df2] , axis=1)

key1 key2  key3 key4  key1   key2  key3      key4
0     1    7    13   19     1      7    13        19
1     2    8    14   20     2      8    14        20
2     3    9    15   21     3  kumar    15        21
3     4   10    16   22     4     10    16   ineuron
4     5   11    17   23     5     11    17  pwskills
5  sudh   12    18   24  sudh     12    18        24

In [40]:
import numpy as np 

In [41]:
l = [1,2,3,4,4]


In [42]:
type(l)

list

In [43]:
a = np.array(l)

In [44]:
type(a)

numpy.ndarray

In [45]:
a

array([1, 2, 3, 4, 4])

In [46]:
a1 = np.array([[1,2,3] , [3,4,5]])

In [47]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [48]:
a2 = np.array([[[1,2,3] , [4,.5,6]]])

In [49]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [50]:
a

array([1, 2, 3, 4, 4])

In [51]:
a1


array([[1, 2, 3],
       [3, 4, 5]])

In [52]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [53]:
a.ndim

1

In [54]:
a1.ndim

2

In [55]:
a2.ndim

3

In [56]:
a3 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])

In [57]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [58]:
a3.ndim

3

In [59]:
l = [1,2,3,4]

In [60]:
a = np.asarray(l)

In [61]:
m = np.matrix(l)

In [62]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [63]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [64]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [65]:
a

array([1, 2, 3, 4])

In [66]:
a1 = a

In [67]:
a1

array([1, 2, 3, 4])

In [68]:
a

array([1, 2, 3, 4])

In [69]:
a[0] = 10

In [70]:
a

array([10,  2,  3,  4])

In [71]:
a1

array([10,  2,  3,  4])

In [72]:
a1[3] = 50

In [73]:
a1

array([10,  2,  3, 50])

In [74]:
a

array([10,  2,  3, 50])

In [75]:
a2 = np.copy(a)

In [76]:
a2

array([10,  2,  3, 50])

In [77]:
a2[2] = 30

In [78]:
a2

array([10,  2, 30, 50])

In [79]:
a

array([10,  2,  3, 50])

In [80]:
np.fromfunction(lambda i,j : i==j , (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [81]:
np.fromfunction(lambda i,j: i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [82]:
np.random.rand(2,3,2)

array([[[0.19734699, 0.16039293],
        [0.15911475, 0.41112402],
        [0.66526409, 0.18510971]],

       [[0.70578947, 0.3024568 ],
        [0.74255764, 0.56299537],
        [0.3420689 , 0.44749589]]])

In [83]:
np.random.rand(2,3,2,2)

array([[[[0.36836524, 0.0716723 ],
         [0.2119978 , 0.2270815 ]],

        [[0.78690566, 0.58709851],
         [0.42808793, 0.77354593]],

        [[0.80760265, 0.2384434 ],
         [0.94467133, 0.48951969]]],


       [[[0.9050757 , 0.56872907],
         [0.38837784, 0.80181369]],

        [[0.99565586, 0.55274116],
         [0.10209825, 0.76003393]],

        [[0.46042567, 0.9410508 ],
         [0.42684497, 0.59584572]]]])

In [84]:
np.random.rand(3,4,5)

array([[[0.41475227, 0.47056972, 0.78405714, 0.52463736, 0.59819412],
        [0.67333672, 0.49955208, 0.68162558, 0.54249746, 0.13344839],
        [0.1858935 , 0.97039442, 0.86882538, 0.49166435, 0.32626219],
        [0.12621702, 0.96866979, 0.75479594, 0.26397849, 0.75331738]],

       [[0.20243986, 0.88728417, 0.41122232, 0.52136835, 0.54373169],
        [0.77349246, 0.54625489, 0.70924104, 0.05253483, 0.97630526],
        [0.92456749, 0.9255689 , 0.22136316, 0.44708071, 0.90365182],
        [0.21453685, 0.05611109, 0.39488073, 0.19806935, 0.55954173]],

       [[0.71741528, 0.40992281, 0.37660762, 0.10174209, 0.53053884],
        [0.55204167, 0.23933892, 0.33947988, 0.42081142, 0.206026  ],
        [0.86254654, 0.29769276, 0.55409519, 0.96251073, 0.90870706],
        [0.78087261, 0.69567184, 0.899657  , 0.20958725, 0.05555035]]])

In [85]:
d = np.random.randn(3,4)

In [86]:
d

array([[-0.32090869,  0.82004835,  0.84649778, -0.21143793],
       [ 3.6723863 ,  0.098386  ,  0.99696303,  1.46694483],
       [-0.88897806,  1.20797857,  0.65210113,  0.23683022]])

In [87]:
pd.DataFrame(d)

0         1         2         3
0 -0.320909  0.820048  0.846498 -0.211438
1  3.672386  0.098386  0.996963  1.466945
2 -0.888978  1.207979  0.652101  0.236830

In [88]:
d1=np.random.randint(0,10,(4,4,2))

In [89]:
d1

array([[[0, 1],
        [3, 5],
        [9, 8],
        [9, 7]],

       [[4, 9],
        [1, 3],
        [9, 7],
        [0, 1]],

       [[9, 0],
        [8, 5],
        [6, 3],
        [7, 1]],

       [[9, 1],
        [1, 8],
        [7, 0],
        [7, 7]]])

In [90]:
d1.reshape(16,2)

array([[0, 1],
       [3, 5],
       [9, 8],
       [9, 7],
       [4, 9],
       [1, 3],
       [9, 7],
       [0, 1],
       [9, 0],
       [8, 5],
       [6, 3],
       [7, 1],
       [9, 1],
       [1, 8],
       [7, 0],
       [7, 7]])

In [91]:
d1.reshape(8,4)

array([[0, 1, 3, 5],
       [9, 8, 9, 7],
       [4, 9, 1, 3],
       [9, 7, 0, 1],
       [9, 0, 8, 5],
       [6, 3, 7, 1],
       [9, 1, 1, 8],
       [7, 0, 7, 7]])

In [92]:
pd.DataFrame(d1.reshape(32,-1987987))

0
0   0
1   1
2   3
3   5
4   9
5   8
6   9
7   7
8   4
9   9
10  1
11  3
12  9
13  7
14  0
15  1
16  9
17  0
18  8
19  5
20  6
21  3
22  7
23  1
24  9
25  1
26  1
27  8
28  7
29  0
30  7
31  7

In [93]:
pd.DataFrame(d1)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [96]:
d1 = d1.reshape(8,4)

In [97]:
pd.DataFrame(d1)

0  1  2  3
0  0  1  3  5
1  9  8  9  7
2  4  9  1  3
3  9  7  0  1
4  9  0  8  5
5  6  3  7  1
6  9  1  1  8
7  7  0  7  7